// Generated by https://quicktype.io

export interface Alumn {
  apellidos:             string;
  nombre:                string;
  registrosViajes:       RegistrosViaje[];
  numTel:                string;
  email:                 string;
  idCarrera:             number;
  fechaNac:              FechaNac;
  contactosDeEmergencia: ContactosDeEmergencia[];
}

export interface ContactosDeEmergencia {
  nombre: string;
  numTel: string;
}

export interface FechaNac {
  seconds:     number;
  nanoseconds: number;
}

export interface RegistrosViaje {
  idViaje:    number;
  horaBajada: FechaNac;
  horaSubida: FechaNac;
}
